name: GitHub Actions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
