name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the version of Node.js to use

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 6: Build the Astro project
      - name: Build Astro project
        run: npm run build

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Astro 默認的建置目錄

      # Optional Step: Deploy or run tests (if applicable)
      # Uncomment and customize if deploying the site or running tests
      # - name: Run tests
      #   run: npm test

      # - name: Deploy to a service (e.g., Netlify, Vercel)
      #   run: npm run deploy  # Customize based on your deployment needs
